# Page settings

baseURL = 'https://sbwiecko.github.io/cv/'
languageCode = 'en-us'
title = 'my CV'
theme = 'hugo-orbit-theme'

# Do not build files for websites. Need them? Set to false
disableRSS = true
disableSitemap = true
disable404 = true

[params]

# Meta
    description = "my CV"
    author = "Sébastien Wieckowski"

# Theme styles

    # The original template comes with 6 colour schemes. You may choose styles below.
    # "styles.css", "styles-2.css", "styles-3.css", "styles-4.css", "styles-5.css", "styles-6.css"
    # are available. Also the source LESS files are included so
    # it’s quick and easy to change the styling and colour scheme.

    styles = "styles-6.css"

# Sidebar sections

    # Profile section
    [params.profile]
        name = "Sébastien Wieckowski, Ph.D."
        tagline = "immunologist, age 43, French/EU citizenship, married and one child"
        avatar = "profile-pic.png"

    # Contact section
    [params.contact]
        enable = true

        [[params.contact.list]]
        class = "email"
        icon = "fa-envelope"
        url = "mailto: sbwiecko@gmail.com"
        title = "sbwiecko@gmail.com"

        [[params.contact.list]]
        class = "phone"
        icon = "fa-phone"
        url = "tel:+33767137882"
        title = "+33 7 67 13 78 82"

        [[params.contact.list]]
        class = "linkedin"
        icon = "fa-linkedin"
        url = "//linkedin.com/in/sbwiecko"
        title = "sbwiecko"

        [[params.contact.list]]
        class = "twitter"
        icon = "fa-twitter"
        url = "//twitter.com/sbwiecko"
        title = "@sbwiecko"

        [[params.contact.list]]
        class = "scholar"
        icon = "fa-graduation-cap"
        url = "//scholar.google.com/citations?user=fzECT2QAAAAJ&hl=en"
        title = "Google Scholar"

        [[params.contact.list]]
        class = "researchgate"
        icon = "fa-graduation-cap"
        url = "//www.researchgate.net/profile/Sebastien_Wieckowski"
        title = "researchgate"

        [[params.contact.list]]
        class = "github"
        icon = "fa-github"
        url = "//github.com/sbwiecko"
        title = "github.com/sbwiecko"

        [[params.contact.list]]
        class = "stack-overflow"
        icon = "fa-stack-overflow"
        url = "//stackoverflow.com/users/8275142/s%c3%a9bastien-wieckowski"
        title = "user/8275142"

    # Education section
    [params.education]
        enable = true
        title = "Education"

        [[params.education.list]]
        degree = "Ph.D. in Immunology"
        college = "Université Strasbourg, France"
        dates = "2003 - 2007"

        [[params.education.list]]
        degree = "Master Degree in Health Biology"
        college = "Université Montpellier II, France"
        dates = "2002 - 2003"

        [[params.education.list]]
        degree = "M.Sc. in Biochemistry + Organic Chemistry"
        college = "Université Montpellier II, France"
        dates = "2001 - 2002"

        [[params.education.list]]
        degree = "B.Sc. in Biochemistry + Bioinformatics (Summa Cum Laude)"
        college = "Université Montpellier II, France"
        dates = "2000 - 2001"

    # Languages section
    [params.language]
        enable = true
        title = "Languages"

        [[params.language.list]]
        language = "French"
        level = "native"

        [[params.language.list]]
        language = "English"
        level = "professional"

        [[params.language.list]]
        language = "German"
        level = "elementary"

        [[params.language.list]]
        language = "Polish"
        level = "elementary"


# Main body sections

    # You may use markdown in summary, details and intro fields. But don't overdose, it's resume!:)
    # see the params.yaml content

    # Summary section
    [params.summary]
        enable = false
        icon = "fa-user"
        title = "Career Profile"
        summary = ""

    [params.footer]
        copyright = "Sébastien Wieckowski"